name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration - Static Analysis", "Continuous Integration ‑ Audit"]
    types: [completed]
    branches: [main]

concurrency:
  group: deployment
  cancel-in-progress: false

env:
  WASM_TARGET: wasm32-unknown-unknown
  TRUNK_OUTPUT_DIR: dist

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.name == 'Continuous Integration - Static Analysis' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
          target: ${{ env.WASM_TARGET }}

      - name: Cache cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            target
          key: deployment-${{ hashFiles('**/Cargo.lock') }}

      - name: Install trunk
        run: cargo install trunk --locked

      - name: Build
        run: trunk build --release --public-url "/${{ github.event.repository.name }}/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.TRUNK_OUTPUT_DIR }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
